#!/usr/bin/env bash
# =============================================================================
# Smart Telegram Monitor for Elastos Block Explorer
#
# Cron (installed by setup-server.sh):
#   * * * * * /opt/ela-explorer/ela-explorer/scripts/tg-monitor.sh >> /var/log/ela-monitor.log 2>&1
#
# Capabilities:
#   - 9 health checks covering every layer of the stack
#   - State-based alerting: only alerts on state transitions (no spam)
#   - Escalation: reminders at 5m, 15m, 1h, then hourly
#   - Recovery notifications when things come back
#   - Auto-fix engine with safety cooldowns
#   - Combined alerts (multiple issues in one message)
#
# Config: /etc/ela-monitor.conf
# State:  /var/lib/ela-monitor/state
# Log:    /var/log/ela-monitor.log
# =============================================================================
set -uo pipefail

CONFIG_FILE="/etc/ela-monitor.conf"
STATE_DIR="/var/lib/ela-monitor"
STATE_FILE="$STATE_DIR/state"
FIX_STATE_FILE="$STATE_DIR/fix_state"
LOG_FILE="/var/log/ela-monitor.log"

# Escalation schedule (seconds since first alert for that issue)
REMIND_INTERVALS=(300 900 3600)
REMIND_LOOP=3600

# Auto-fix cooldowns (seconds)
COOLDOWN_NODE=600
COOLDOWN_PG=600
COOLDOWN_CONTAINER=300
COOLDOWN_NGINX=300
MAX_CONSECUTIVE_FIXES=3

NOW=$(date +%s)
NOW_HUMAN=$(date '+%Y-%m-%d %H:%M:%S UTC')

# =========================================================================
# Load config
# =========================================================================
if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "[$NOW_HUMAN] FATAL: Config not found: $CONFIG_FILE" >> "$LOG_FILE"
    exit 1
fi
source "$CONFIG_FILE"

ELA_NODE_DIR="${ELA_NODE_DIR:-/root/node}"
EXPLORER_DIR="${EXPLORER_DIR:-/opt/ela-explorer/backend-src}"
RPC_USER="${RPC_USER:-}"
RPC_PASS="${RPC_PASS:-}"

if [[ -n "$RPC_USER" && -n "$RPC_PASS" ]]; then
    NODE_RPC="http://${RPC_USER}:${RPC_PASS}@127.0.0.1:20336"
else
    NODE_RPC="http://127.0.0.1:20336"
fi

mkdir -p "$STATE_DIR"

# =========================================================================
# Telegram
# =========================================================================
send_tg() {
    local text="$1"
    if [[ -z "${TG_TOKEN:-}" || "${TG_TOKEN}" == "bot_token_here" || -z "${TG_CHAT:-}" || "${TG_CHAT}" == "chat_id_here" ]]; then
        return 0
    fi
    curl -s -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
        -d chat_id="${TG_CHAT}" \
        -d text="$text" \
        -d parse_mode="HTML" \
        --max-time 10 > /dev/null 2>&1 || true
}

# =========================================================================
# State management
# =========================================================================
load_state() {
    if [[ -f "$STATE_FILE" ]]; then
        source "$STATE_FILE"
    fi
    if [[ -f "$FIX_STATE_FILE" ]]; then
        source "$FIX_STATE_FILE"
    fi
}

save_state() {
    cat > "$STATE_FILE" <<EOF
# Auto-generated by tg-monitor.sh — do not edit
# Last run: $NOW_HUMAN

# Per-check state: STATUS_<check>=ok|warning|critical
# SINCE_<check>=epoch when current status started
# LASTALERT_<check>=epoch of last alert sent
# ALERTCOUNT_<check>=number of alerts sent for current issue
# LASTMSG_<check>=hash of last message content

$(for check in ela_node postgresql container api nginx sync_stall node_gap disk memory; do
    eval "echo \"STATUS_${check}=\${CUR_STATUS_${check}:-ok}\""
    eval "echo \"SINCE_${check}=\${CUR_SINCE_${check}:-$NOW}\""
    eval "echo \"LASTALERT_${check}=\${CUR_LASTALERT_${check}:-0}\""
    eval "echo \"ALERTCOUNT_${check}=\${CUR_ALERTCOUNT_${check}:-0}\""
    eval "echo \"LASTMSG_${check}=\${CUR_LASTMSG_${check}:-}\""
done)

# Sync tracking
PREV_SYNC_HEIGHT=${CUR_SYNC_HEIGHT:-0}
PREV_SYNC_TIME=${NOW}
PREV_NODE_HEIGHT=${CUR_NODE_HEIGHT:-0}
EOF
}

save_fix_state() {
    cat > "$FIX_STATE_FILE" <<EOF
# Auto-fix tracking — do not edit
$(for svc in ela_node postgresql container nginx; do
    eval "echo \"FIXTIME_${svc}=\${FIXTIME_${svc}:-0}\""
    eval "echo \"FIXCOUNT_${svc}=\${FIXCOUNT_${svc}:-0}\""
done)
EOF
}

# Get previous state for a check
prev_status()  { eval "echo \${STATUS_${1}:-ok}"; }
prev_since()   { eval "echo \${SINCE_${1}:-$NOW}"; }
prev_alert()   { eval "echo \${LASTALERT_${1}:-0}"; }
prev_count()   { eval "echo \${ALERTCOUNT_${1}:-0}"; }
prev_msg()     { eval "echo \${LASTMSG_${1}:-}"; }

# Set current state for a check
set_status() {
    local check="$1" status="$2"
    eval "CUR_STATUS_${check}='$status'"

    local old_status
    old_status=$(prev_status "$check")

    if [[ "$old_status" == "$status" ]]; then
        eval "CUR_SINCE_${check}=$(prev_since "$check")"
        eval "CUR_LASTALERT_${check}=$(prev_alert "$check")"
        eval "CUR_ALERTCOUNT_${check}=$(prev_count "$check")"
    else
        eval "CUR_SINCE_${check}=$NOW"
        eval "CUR_LASTALERT_${check}=0"
        eval "CUR_ALERTCOUNT_${check}=0"
    fi
}

# =========================================================================
# Smart alerting: should we send an alert for this check?
# =========================================================================
should_alert() {
    local check="$1" new_status="$2" msg_hash="$3"
    local old_status last_alert alert_count since

    old_status=$(prev_status "$check")
    last_alert=$(eval "echo \${CUR_LASTALERT_${check}:-0}")
    alert_count=$(eval "echo \${CUR_ALERTCOUNT_${check}:-0}")
    since=$(eval "echo \${CUR_SINCE_${check}:-$NOW}")

    # ok -> ok: silence
    if [[ "$new_status" == "ok" && "$old_status" == "ok" ]]; then
        return 1
    fi

    # problem -> ok: recovery alert (always)
    if [[ "$new_status" == "ok" && "$old_status" != "ok" ]]; then
        return 0
    fi

    # ok -> problem: immediate alert
    if [[ "$new_status" != "ok" && "$old_status" == "ok" ]]; then
        return 0
    fi

    # Different problem text: new alert
    local old_msg
    old_msg=$(prev_msg "$check")
    if [[ -n "$msg_hash" && "$msg_hash" != "$old_msg" && "$alert_count" -gt 0 ]]; then
        return 0
    fi

    # Same problem persisting: check escalation schedule
    if [[ "$last_alert" -eq 0 ]]; then
        return 0
    fi

    local elapsed=$((NOW - since))
    local since_last_alert=$((NOW - last_alert))

    # Walk the escalation intervals
    for interval in "${REMIND_INTERVALS[@]}"; do
        if [[ "$elapsed" -ge "$interval" && "$alert_count" -le "${#REMIND_INTERVALS[@]}" && "$since_last_alert" -ge "$interval" ]]; then
            return 0
        fi
    done

    # After all intervals exhausted, remind every REMIND_LOOP seconds
    if [[ "$since_last_alert" -ge "$REMIND_LOOP" ]]; then
        return 0
    fi

    return 1
}

record_alert() {
    local check="$1" msg_hash="$2"
    local count
    count=$(eval "echo \${CUR_ALERTCOUNT_${check}:-0}")
    eval "CUR_LASTALERT_${check}=$NOW"
    eval "CUR_ALERTCOUNT_${check}=$((count + 1))"
    eval "CUR_LASTMSG_${check}='$msg_hash'"
}

# =========================================================================
# Auto-fix engine
# =========================================================================
can_autofix() {
    local svc="$1" cooldown="$2"
    local last_fix fix_count
    last_fix=$(eval "echo \${FIXTIME_${svc}:-0}")
    fix_count=$(eval "echo \${FIXCOUNT_${svc}:-0}")

    if [[ $((NOW - last_fix)) -lt "$cooldown" ]]; then
        return 1
    fi
    if [[ "$fix_count" -ge "$MAX_CONSECUTIVE_FIXES" ]]; then
        return 1
    fi
    return 0
}

record_fix() {
    local svc="$1"
    local count
    count=$(eval "echo \${FIXCOUNT_${svc}:-0}")
    eval "FIXTIME_${svc}=$NOW"
    eval "FIXCOUNT_${svc}=$((count + 1))"
}

reset_fixes() {
    local svc="$1"
    eval "FIXCOUNT_${svc}=0"
}

try_autofix() {
    local svc="$1" cooldown="$2" action="$3" desc="$4"

    if ! can_autofix "$svc" "$cooldown"; then
        local fix_count
        fix_count=$(eval "echo \${FIXCOUNT_${svc}:-0}")
        if [[ "$fix_count" -ge "$MAX_CONSECUTIVE_FIXES" ]]; then
            echo "MANUAL_NEEDED"
        else
            echo "COOLDOWN"
        fi
        return 1
    fi

    echo "[$NOW_HUMAN] AUTO-FIX: $desc" >> "$LOG_FILE"
    record_fix "$svc"

    if eval "$action" >> "$LOG_FILE" 2>&1; then
        sleep 30

        echo "ATTEMPTED"
        return 0
    else
        echo "FAILED"
        return 1
    fi
}

# =========================================================================
# RPC helper
# =========================================================================
rpc_call() {
    curl -s -m 5 -X POST "$NODE_RPC" \
        -H "Content-Type: application/json" \
        -d "{\"method\":\"$1\"}" 2>/dev/null
}

# =========================================================================
# Health Checks
# =========================================================================
ISSUES=()
RECOVERIES=()

load_state

# --- Check 1: ELA Node ---
check_ela_node() {
    local height
    height=$(rpc_call "getblockcount" | grep -o '"result":[0-9]*' | grep -o '[0-9]*' || true)

    CUR_NODE_HEIGHT="${height:-0}"

    if [[ -z "$height" || "$height" == "0" ]]; then
        set_status "ela_node" "critical"
        local msg="ELA Node RPC unreachable (127.0.0.1:20336)"
        local msg_hash
        msg_hash=$(echo -n "ela_node_down" | md5sum | cut -d' ' -f1 2>/dev/null || echo "ela_node_down")

        local fix_result=""
        if [[ -x "$ELA_NODE_DIR/node.sh" ]]; then
            fix_result=$(try_autofix "ela_node" "$COOLDOWN_NODE" "'$ELA_NODE_DIR/node.sh' ela start" "Starting ELA node via node.sh") || true
        fi

        if [[ "$fix_result" == "ATTEMPTED" ]]; then
            local recheck
            recheck=$(rpc_call "getblockcount" | grep -o '"result":[0-9]*' | grep -o '[0-9]*' || true)
            if [[ -n "$recheck" && "$recheck" != "0" ]]; then
                msg="ELA Node was down — auto-restarted successfully (height: $recheck)"
                set_status "ela_node" "ok"
                reset_fixes "ela_node"
            else
                msg="ELA Node DOWN — auto-restart attempted but node still unresponsive"
            fi
        elif [[ "$fix_result" == "MANUAL_NEEDED" ]]; then
            msg="ELA Node DOWN — auto-restart failed ${MAX_CONSECUTIVE_FIXES}x, MANUAL ATTENTION REQUIRED"
        fi

        if should_alert "ela_node" "$(eval "echo \${CUR_STATUS_ela_node}")" "$msg_hash"; then
            ISSUES+=("$msg")
            record_alert "ela_node" "$msg_hash"
        fi
    else
        if [[ "$(prev_status ela_node)" != "ok" ]]; then
            RECOVERIES+=("ELA Node recovered (height: $height)")
            reset_fixes "ela_node"
        fi
        set_status "ela_node" "ok"
    fi
}

# --- Check 2: PostgreSQL ---
check_postgresql() {
    if pg_isready -h 127.0.0.1 -q 2>/dev/null; then
        if [[ "$(prev_status postgresql)" != "ok" ]]; then
            RECOVERIES+=("PostgreSQL recovered")
            reset_fixes "postgresql"
        fi
        set_status "postgresql" "ok"
    else
        set_status "postgresql" "critical"
        local msg="PostgreSQL not accepting connections"
        local msg_hash="pg_down"

        # Only auto-fix if no pg_dump is running
        if ! pgrep -x pg_dump > /dev/null 2>&1; then
            local fix_result=""
            fix_result=$(try_autofix "postgresql" "$COOLDOWN_PG" "systemctl restart postgresql" "Restarting PostgreSQL") || true

            if [[ "$fix_result" == "ATTEMPTED" ]]; then
                if pg_isready -h 127.0.0.1 -q 2>/dev/null; then
                    msg="PostgreSQL was down — auto-restarted successfully"
                    set_status "postgresql" "ok"
                    reset_fixes "postgresql"
                else
                    msg="PostgreSQL DOWN — auto-restart attempted but still unresponsive"
                fi
            elif [[ "$fix_result" == "MANUAL_NEEDED" ]]; then
                msg="PostgreSQL DOWN — auto-restart failed ${MAX_CONSECUTIVE_FIXES}x, MANUAL ATTENTION REQUIRED"
            fi
        else
            msg="PostgreSQL not responding (pg_dump running — skipping auto-restart)"
        fi

        if should_alert "postgresql" "$(eval "echo \${CUR_STATUS_postgresql}")" "$msg_hash"; then
            ISSUES+=("$msg")
            record_alert "postgresql" "$msg_hash"
        fi
    fi
}

# --- Check 3: Explorer Container ---
check_container() {
    local running
    running=$(docker ps --filter name=ela-explorer --format '{{.Status}}' 2>/dev/null || true)

    if echo "$running" | grep -qi "Up"; then
        if [[ "$(prev_status container)" != "ok" ]]; then
            RECOVERIES+=("Explorer container recovered")
            reset_fixes "container"
        fi
        set_status "container" "ok"
    else
        set_status "container" "critical"
        local msg="Explorer container is DOWN"
        local msg_hash="container_down"

        local fix_result=""
        fix_result=$(try_autofix "container" "$COOLDOWN_CONTAINER" \
            "docker compose -f '$EXPLORER_DIR/docker-compose.yml' --env-file '$(dirname "$EXPLORER_DIR")/.env' up -d" \
            "Starting Explorer container") || true

        if [[ "$fix_result" == "ATTEMPTED" ]]; then
            local recheck
            recheck=$(docker ps --filter name=ela-explorer --format '{{.Status}}' 2>/dev/null || true)
            if echo "$recheck" | grep -qi "Up"; then
                msg="Explorer container was down — auto-restarted successfully"
                set_status "container" "ok"
                reset_fixes "container"
            else
                msg="Explorer container DOWN — auto-restart attempted but still not running"
            fi
        elif [[ "$fix_result" == "MANUAL_NEEDED" ]]; then
            msg="Explorer container DOWN — auto-restart failed ${MAX_CONSECUTIVE_FIXES}x, MANUAL ATTENTION REQUIRED"
        fi

        if should_alert "container" "$(eval "echo \${CUR_STATUS_container}")" "$msg_hash"; then
            ISSUES+=("$msg")
            record_alert "container" "$msg_hash"
        fi
    fi
}

# --- Check 4: API Health ---
check_api() {
    local status_code
    status_code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "http://127.0.0.1:8339/health" 2>/dev/null || echo "000")

    if [[ "$status_code" == "200" ]]; then
        if [[ "$(prev_status api)" != "ok" ]]; then
            RECOVERIES+=("API /health recovered (HTTP 200)")
        fi
        set_status "api" "ok"
    else
        set_status "api" "critical"
        local msg="API /health returned HTTP $status_code"
        local msg_hash="api_$status_code"

        if should_alert "api" "$(eval "echo \${CUR_STATUS_api}")" "$msg_hash"; then
            ISSUES+=("$msg")
            record_alert "api" "$msg_hash"
        fi
    fi
}

# --- Check 5: Nginx ---
check_nginx() {
    # UFW on this server blocks port 80/443 from all IPs except Cloudflare,
    # including localhost — so curl http://127.0.0.1/ always returns 000.
    # Use systemctl process state as the sole nginx health indicator.
    local nginx_active
    nginx_active=$(systemctl is-active nginx 2>/dev/null || true)

    if [[ "$nginx_active" == "active" ]]; then
        if [[ "$(prev_status nginx)" != "ok" ]]; then
            RECOVERIES+=("Nginx recovered")
            reset_fixes "nginx"
        fi
        set_status "nginx" "ok"
    else
        set_status "nginx" "warning"
        local msg="Nginx process not active (state: $nginx_active)"
        local msg_hash="nginx_${nginx_active}"

        local fix_result=""
        fix_result=$(try_autofix "nginx" "$COOLDOWN_NGINX" "systemctl restart nginx" "Restarting Nginx") || true

        if [[ "$fix_result" == "ATTEMPTED" ]]; then
            local recheck_active
            recheck_active=$(systemctl is-active nginx 2>/dev/null || true)
            if [[ "$recheck_active" == "active" ]]; then
                msg="Nginx was down — auto-restarted successfully"
                set_status "nginx" "ok"
                reset_fixes "nginx"
            fi
        fi

        if should_alert "nginx" "$(eval "echo \${CUR_STATUS_nginx}")" "$msg_hash"; then
            ISSUES+=("$msg")
            record_alert "nginx" "$msg_hash"
        fi
    fi
}

# --- Check 6: Sync Stall ---
check_sync_stall() {
    local stats
    stats=$(curl -s --max-time 5 "http://127.0.0.1:8339/api/v1/sync-status" 2>/dev/null || true)

    if [[ -z "$stats" ]]; then
        return
    fi

    local current_height
    current_height=$(echo "$stats" | grep -o '"currentHeight":[0-9]*' | grep -o '[0-9]*' | head -1 || true)
    CUR_SYNC_HEIGHT="${current_height:-0}"

    local prev_height="${PREV_SYNC_HEIGHT:-0}"
    local prev_time="${PREV_SYNC_TIME:-$NOW}"
    local elapsed_min=$(( (NOW - prev_time) / 60 ))

    if [[ -n "$current_height" && "$current_height" -gt 0 && "$current_height" -eq "$prev_height" && "$elapsed_min" -ge 15 ]]; then
        set_status "sync_stall" "warning"
        local chain_tip
        chain_tip=$(echo "$stats" | grep -o '"chainTip":[0-9]*' | grep -o '[0-9]*' | head -1 || true)
        local msg="Sync stalled at height $current_height for ${elapsed_min}m (chain tip: ${chain_tip:-?})"
        local msg_hash="stall_$current_height"

        if should_alert "sync_stall" "warning" "$msg_hash"; then
            ISSUES+=("$msg")
            record_alert "sync_stall" "$msg_hash"
        fi
    else
        if [[ "$(prev_status sync_stall)" != "ok" ]]; then
            RECOVERIES+=("Sync resumed (height: ${current_height:-?})")
        fi
        set_status "sync_stall" "ok"
    fi
}

# --- Check 7: Node Sync Gap (local vs reference RPCs) ---
check_node_gap() {
    local local_height="${CUR_NODE_HEIGHT:-0}"
    if [[ "$local_height" -eq 0 ]]; then
        return
    fi

    local ref_height=0
    for ref_url in "https://rpc.elastos.info/ela" "https://api.elastos.io/ela"; do
        local h
        h=$(curl -s -m 5 -X POST "$ref_url" \
            -H "Content-Type: application/json" \
            -d '{"method":"getblockcount"}' 2>/dev/null | grep -o '"result":[0-9]*' | grep -o '[0-9]*' || true)
        if [[ -n "$h" && "$h" -gt "$ref_height" ]]; then
            ref_height="$h"
        fi
    done

    if [[ "$ref_height" -gt 0 ]]; then
        local gap=$((ref_height - local_height))
        if [[ "$gap" -gt 50 ]]; then
            set_status "node_gap" "warning"
            local msg="Node $gap blocks behind network (local: $local_height, network: $ref_height)"
            local msg_hash="gap_${gap}"

            if should_alert "node_gap" "warning" "$msg_hash"; then
                ISSUES+=("$msg")
                record_alert "node_gap" "$msg_hash"
            fi
        else
            if [[ "$(prev_status node_gap)" != "ok" ]]; then
                RECOVERIES+=("Node caught up with network (height: $local_height)")
            fi
            set_status "node_gap" "ok"
        fi
    fi
}

# --- Check 8: Disk Usage ---
check_disk() {
    local usage
    usage=$(df /opt --output=pcent 2>/dev/null | tail -1 | tr -d ' %' || true)

    if [[ -z "$usage" ]]; then
        return
    fi

    if [[ "$usage" -gt 95 ]]; then
        set_status "disk" "critical"
        local msg="CRITICAL disk usage: ${usage}% on /opt"
        local msg_hash="disk_crit_$usage"
        if should_alert "disk" "critical" "$msg_hash"; then
            ISSUES+=("$msg")
            record_alert "disk" "$msg_hash"
        fi
    elif [[ "$usage" -gt 85 ]]; then
        set_status "disk" "warning"
        local msg="Disk usage high: ${usage}% on /opt"
        local msg_hash="disk_warn_$usage"
        if should_alert "disk" "warning" "$msg_hash"; then
            ISSUES+=("$msg")
            record_alert "disk" "$msg_hash"
        fi
    else
        if [[ "$(prev_status disk)" != "ok" ]]; then
            RECOVERIES+=("Disk usage back to normal: ${usage}%")
        fi
        set_status "disk" "ok"
    fi
}

# --- Check 9: Memory Usage ---
check_memory() {
    local mem_total mem_avail pct_used
    mem_total=$(grep MemTotal /proc/meminfo 2>/dev/null | awk '{print $2}' || true)
    mem_avail=$(grep MemAvailable /proc/meminfo 2>/dev/null | awk '{print $2}' || true)

    if [[ -z "$mem_total" || -z "$mem_avail" || "$mem_total" -eq 0 ]]; then
        return
    fi

    pct_used=$(( (mem_total - mem_avail) * 100 / mem_total ))

    if [[ "$pct_used" -gt 95 ]]; then
        set_status "memory" "critical"
        local msg="CRITICAL memory usage: ${pct_used}%"
        local msg_hash="mem_crit"
        if should_alert "memory" "critical" "$msg_hash"; then
            ISSUES+=("$msg")
            record_alert "memory" "$msg_hash"
        fi
    elif [[ "$pct_used" -gt 90 ]]; then
        set_status "memory" "warning"
        local msg="Memory usage high: ${pct_used}%"
        local msg_hash="mem_warn"
        if should_alert "memory" "warning" "$msg_hash"; then
            ISSUES+=("$msg")
            record_alert "memory" "$msg_hash"
        fi
    else
        if [[ "$(prev_status memory)" != "ok" ]]; then
            RECOVERIES+=("Memory usage back to normal: ${pct_used}%")
        fi
        set_status "memory" "ok"
    fi
}

# =========================================================================
# Run all checks
# =========================================================================
CUR_NODE_HEIGHT=0
CUR_SYNC_HEIGHT=0

check_ela_node
check_postgresql
check_container
check_api
check_nginx
check_sync_stall
check_node_gap
check_disk
check_memory

# =========================================================================
# Send combined alerts
# =========================================================================

# Recovery messages
if [[ ${#RECOVERIES[@]} -gt 0 ]]; then
    RECOVERY_TEXT="✅ <b>ELA Explorer RECOVERED</b>"
    for r in "${RECOVERIES[@]}"; do
        RECOVERY_TEXT="${RECOVERY_TEXT}%0A• ${r}"
    done
    RECOVERY_TEXT="${RECOVERY_TEXT}%0A%0ATime: $NOW_HUMAN"
    send_tg "$RECOVERY_TEXT"
fi

# Issue messages
if [[ ${#ISSUES[@]} -gt 0 ]]; then
    SEVERITY="⚠️"
    for check in ela_node postgresql container api nginx sync_stall node_gap disk memory; do
        local_status=$(eval "echo \${CUR_STATUS_${check}:-ok}")
        if [[ "$local_status" == "critical" ]]; then
            SEVERITY="🔴"
            break
        fi
    done

    ISSUE_TEXT="${SEVERITY} <b>ELA Explorer Alert</b>"
    for i in "${ISSUES[@]}"; do
        ISSUE_TEXT="${ISSUE_TEXT}%0A• ${i}"
    done

    # Append status summary
    ISSUE_TEXT="${ISSUE_TEXT}%0A%0ANode: ${CUR_NODE_HEIGHT:-?} | Sync: ${CUR_SYNC_HEIGHT:-?}"
    ISSUE_TEXT="${ISSUE_TEXT}%0ATime: $NOW_HUMAN"

    send_tg "$ISSUE_TEXT"
fi

# =========================================================================
# Save state and log
# =========================================================================
save_state
save_fix_state

if [[ ${#ISSUES[@]} -eq 0 && ${#RECOVERIES[@]} -eq 0 ]]; then
    echo "[$NOW_HUMAN] OK: all 9 checks passed"
else
    if [[ ${#ISSUES[@]} -gt 0 ]]; then
        echo "[$NOW_HUMAN] ISSUES: ${ISSUES[*]}"
    fi
    if [[ ${#RECOVERIES[@]} -gt 0 ]]; then
        echo "[$NOW_HUMAN] RECOVERED: ${RECOVERIES[*]}"
    fi
fi
