INSERT INTO address_labels (address, label, category) VALUES
    ('8VYXVxKKSAxkmRrfmGpQR2Kc66XhG6m3ta', 'Elastos Foundation (Legacy)', 'foundation'),
    ('CRASSETSXXXXXXXXXXXXXXXXXXXX2qDX5J', 'Elastos DAO Assets (Locked)', 'dao'),
    ('CREXPENSESXXXXXXXXXXXXXXXXXX4UdT6b', 'Elastos DAO Expenses', 'dao'),
    ('ELANULLXXXXXXXXXXXXXXXXXXXXXYvs3rr', 'Burn Address', 'system'),
    ('STAKEPooLXXXXXXXXXXXXXXXXXXXpP1PQ2', 'Staking Pool', 'system'),
    ('STAKEREWARDXXXXXXXXXXXXXXXXXFD5SHU', 'Staking Rewards Pool', 'system'),
    ('XVbCTM7vqM1qHKsABSFH4xKN1qbp7ijpWf', 'ESC Sidechain', 'sidechain'),
    ('XNQWEZ7aqNyJHvav8j8tNo2ZQypuTsWQk6', 'PGP Sidechain', 'sidechain'),
    ('XV5cSp1y1PU4xXSQs5oaaLExgHA2xHYjp5', 'ECO Sidechain', 'sidechain'),
    ('EeKGjcERsZvmRYuJSFbrdvyb8MPzKpL3v6', 'KuCoin Exchange', 'exchange'),
    ('EJyiZrRDhdUtUpkxoLgKmdk8JxKoi1tvHG', 'KuCoin Exchange', 'exchange'),
    ('EHpQRE4K4e2UhD55ingFc7TETuve13aWbZ', 'KuCoin Exchange', 'exchange'),
    ('EKk4HeHnLvMpxFiSbjVizcrCB1nVt39Bwe', 'Gate.io Exchange', 'exchange'),
    ('ETsfuQEcNJbmeT5iPXJxJLc7CtipgaEWZQ', 'CoinEX Exchange', 'exchange'),
    ('EfpBYgTZxsrS3qtAApMTuSwW1M2N5ieH7k', 'MEXC Exchange', 'exchange'),
    ('Eeguj3LmsTnTSyFuvM8DXLmjYNBqa6XK4c', 'ViaBTC', 'mining_pool'),
    ('EMWsru8XhpQxJ7CvDzgAea1WroJqskPmqd', 'BTC.com', 'mining_pool'),
    ('EVXNSmx1KzT6Pxzcup3QGh1vCKZckz8XDD', 'BTC.com', 'mining_pool'),
    ('EbEQ1o4fkbqSg5Q4mR1SwHFWTR4WYFUz8P', 'BTC.com', 'mining_pool'),
    ('EfZ6oNo4oKgefbuX3t2dVrH9ME2mR4ZZka', 'Antpool', 'mining_pool'),
    ('EMRKTXN183vwcGbCetvKuUPHMyQScRjx6F', 'Antpool', 'mining_pool'),
    ('ETAXSN3kc3N3npEeUzMn4bipwUS3ejooiy', 'Antpool', 'mining_pool'),
    ('EdaNsdRChz1pmwHRvSCcTvGhZKaEuimToL', 'Antpool', 'mining_pool'),
    ('EQ34WaW2RmpZhqSUs4DEmVR1RB3zMiJEWe', 'Antpool', 'mining_pool'),
    ('EPEzY8RqLoHiKB5sXsRLNmMcE6ESqvY6Zq', 'F2Pool', 'mining_pool'),
    ('EexDsiXag2rH4f7VTPNziYdGJdcxCnvGW6', 'Braiins', 'mining_pool'),
    ('EJERhHYJHx3w87TZ6jVbF5vtF1JQ3yMDPh', 'BTC.TOP', 'mining_pool'),
    ('EMzsK7X3MhwG5WeCJFCqBwPtgMtJpBeFKL', 'OKPool', 'mining_pool'),
    ('Eb1Vbp9KNJxNjNRWADjXYyL3pRRHvRdpuV', 'Binance Pool', 'mining_pool'),
    ('ER6iCws5hqmVoSeVugnWLNo28rv4iMVy17', 'Poolin', 'mining_pool')
ON CONFLICT (address) DO UPDATE SET label = EXCLUDED.label, category = EXCLUDED.category;
